import express from "express"
import register, { Login } from "../controller/usercontroller.js"
// import userAuth from "../middleware/Authmiddlewar.js"
import { rateLimit } from 'express-rate-limit'


const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    limit: 100, // Limit each IP to 100 requests per `window` (here, per 15 minutes).
    standardHeaders: 'draft-8', // draft-6: `RateLimit-*` headers; draft-7 & draft-8: combined `RateLimit` header
    legacyHeaders: false, // Disable the `X-RateLimit-*` headers.
    ipv6Subnet: 56, // Set to 60 or 64 to be less aggressive, or 52 or 48 to be more aggressive
    // store: ... , // Redis, Memcached, etc. See below.
})

const router = express.Router()

/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - fullname
 *         - email
 *         - password
 *         - location
 *       properties:
 *         id:
 *           type: string
 *           description: The autogenerated id of user collection
 *         fullname:
 *           type: string
 *           description: Username
 *         email:
 *           type: string
 *           description: User generated email
 *         password:
 *           type: string
 *           description: User generated password should be 6 characters
 *         location:
 *           type: string
 *           description: User location city or country
 *       example:
 *         id: NFEYDIFHGDNBUIKJDFNXHC
 *         fullname: meghna parashar
 *         email: meghna@gmail.com
 *         password: gshsbhsnn
 *         location: london
 */

/**
 * @swagger
 * tags:
 *  name: Auth
 *  description: authentication api
 */
/**
 * @swagger
 * /api/auth/register:
 *   post:
 *     summary: Register new user
 *     tags:
 *       - Auth
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: User created successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       500:
 *         description: Internal server error
 */
/**
 * @swagger
 * /api/auth/login:
 *   post:
 *     summary: login user
 *     tags:
 *       - Auth
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: login successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       500:
 *         description: Internal server error
 */
router.post("/register", limiter, register)
router.post("/login", limiter, Login)
export default router;